### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by ralfw**
Two files which were created during VS code restore will now be ignored.

### CODE REVIEW

**Comment by martinh2011** [comment]
Does it really make sense to exclude these files? Are the tasks and launch settings always personal? I'm wondering because the GitHub [default vs code](https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore) gitignore explicitly not excludes these files, but everything else in .vscode

**Comment by ralfw** [comment]
I was wondering, too. But since those files got generated automatically during a process I thought everybody else runs thru, I thought, their exclusion might be overdue.

What will happen if they are not excluded? I think they'll turn up with anybody who initializes a repo and then get committed and synced. Why should that be?

**Comment by martinh2011** [comment]
I suggest that I'll create a pull request with my tasks.json (building, running unit tests) and  launch.json (start debug session, run the app) and we can see if that could work for all of us or if it's better to not use these project-specific settings, but rely on workspace or user-level settings.

**Comment by ralfw** [comment]
So I'll drop the PR.

**Pull request closed without merging**
